-- hl.monitor({
--   output = "eDP-1",
--   mode = "preferred",
--   position = "auto",
--   -- disabled = true
-- })

-- hl.monitor({
--   output = "HDMI-A-1",
--   mode = "3840x2160@60",
--   position = "auto",
--   scale = 2,
--   disabled = true
-- })
