# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Rclone
exec-once = rclone mount gdrive: /mnt/gdrive/ --daemon

# Since Battery Percent
exec-once = upower -i $(upower -e | grep BAT) | awk '/percentage:/ {print $2}' > /tmp/since.txt
exec-once = date +%s%3N > /tmp/since-time.txt

# Bluetooth
exec-once = bluetooth-autoconnect

# ROG
exec-once = ln -sf /dev/dri/by-path/pci-0000\:06\:00.0-card $HOME/.config/hypr/card
