# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Rclone
#exec-once = rclone mount gdrive1: /mnt/GDrive/ --daemon

# Since Battery Percent
exec-once = upower -i $(upower -e | grep BAT) | awk '/percentage:/ {print $2}' > /tmp/since.txt
exec-once = date +%s%3N > /tmp/since-time.txt

# Bluetooth
exec-once = bluetooth-autoconnect