$lock_cmd = pidof hyprlock || hyprlock 
$suspend_cmd = pidof steam || systemctl suspend || loginctl suspend # fuck nvidia

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
}

# listener {
#     timeout = 1
#     on-resume = hyprctl dispatch dpms on
# }

# Restart AGS
# listener {
#     timeout = 150
#     on-timeout = killall ags ydotool && ags &
# }

listener {
    timeout = 60  #1min
    on-timeout = asusctl -k off
    on-resume = asusctl -k low
}

listener {
    timeout = 180 # 3mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 210 # 3.5 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800 # 30mins
    on-timeout = $suspend_cmd
}
