#!/usr/bin/env bash

sudo_nopasswd() {
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/00_${USER}"
}
remove_nopasswd() {
    sudo sed -i 's/NOPASSWD: //' "/etc/sudoers.d/00_${USER}"
}
