### This file supports bash-style comments, and blank lines.
### PKGs on same line will be sent to `yay` together, unless `-f` is specified.

### Most dependencies have been moved to meta packages as declared in arch-packages.
### Use this file for declaring extra dependencies which you need but are not declared by default.

zsh zoxide fzf lsd bat less # My Shell

tmux
go

bluez-utils bluetooth-autoconnect # Bluetooth
fastfetch btop powertop
# firefox
brave-bin
nautilus ntfs-3g nautilus-code nautilus-open-any-terminal
mpv
tailscale
gnome-system-monitor
gnome-text-editor
ufw

gvfs-smb

pacman-contrib
# qemu
