### This file supports bash-style comments, and blank lines.
### PKGs on same line will be sent to `yay` together, unless `-f` is specified.

### Most dependencies have been moved to meta packages as declared in arch-packages.
### Use this file for declaring extra dependencies which you need but are not declared by default.

linux-zen-headers
zsh zoxide fzf exa # My Shell

bluez-utils bluetooth-autoconnect # Bluetooth
fastfetch btop powertop
firefox
# brave-bin
nautilus ntfs-3g nautilus-code nautilus-open-any-terminal
celluloid
tailscaled
gnome-system-monitor
